# Lab 3.3: Holiday Data Processing and Dataset Merging

**Name:** Zubair Moeen  
**Reg Number:** 22jzele0463  
**Lab:** Machine Learning Lab  
**Lab Supervisor:** Engr.Irshad Ullah  
**University:** UET Peshawar - Campus Nowshera  

## Lab Overview
This notebook prepares the time-series dataset for further machine learning work by adding holiday information. The code normalizes datetime values, loads processed holiday data, drops unnecessary columns, and merges both datasets.

## Learning Objectives
- Load the outlier-identified AEP dataset.
- Create a normalized date column from the Datetime column.
- Load and inspect processed holiday data.
- Merge holiday information with the main time-series dataset.

## Section 1: Dataset Loading and Date Preparation
This section loads the outlier-identified dataset and creates a separate Date column for merging with holiday records.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r'Z:\University\8th Semester\ML Lab\Lab 3\3_Outlier_Identified.csv',parse_dates=['Datetime'])
df.head()

             Datetime   AEP_MW
0 2004-10-01 01:00:00  12379.0
1 2004-10-01 02:00:00  11935.0
2 2004-10-01 03:00:00  11692.0
3 2004-10-01 04:00:00  11597.0
4 2004-10-01 05:00:00  11681.0

In [4]:
# df['Datetime'].dt.normalize() removes the time part from each timestamp and keeps only the date
df['Date'] = df['Datetime'].dt.normalize()

In [5]:
df.iloc[0:50]

              Datetime   AEP_MW       Date
0  2004-10-01 01:00:00  12379.0 2004-10-01
1  2004-10-01 02:00:00  11935.0 2004-10-01
2  2004-10-01 03:00:00  11692.0 2004-10-01
3  2004-10-01 04:00:00  11597.0 2004-10-01
4  2004-10-01 05:00:00  11681.0 2004-10-01
5  2004-10-01 06:00:00  12280.0 2004-10-01
6  2004-10-01 07:00:00  13692.0 2004-10-01
7  2004-10-01 08:00:00  14618.0 2004-10-01
8  2004-10-01 09:00:00  14903.0 2004-10-01
9  2004-10-01 10:00:00  15118.0 2004-10-01
10 2004-10-01 11:00:00  15242.0 2004-10-01
11 2004-10-01 12:00:00  15375.0 2004-10-01
12 2004-10-01 13:00:00  15404.0 2004-10-01
13 2004-10-01 14:00:00  15655.0 2004-10-01
14 2004-10-01 15:00:00  15739.0 2004-10-01
15 2004-10-01 16:00:00  15739.0 2004-10-01
16 2004-10-01 17:00:00  15644.0 2004-10-01
17 2004-10-01 18:00:00  15353.0 2004-10-01
18 2004-10-01 19:00:00  15034.0 2004-10-01
19 2004-10-01 20:00:00  15211.0 2004-10-01
20 2004-10-01 21:00:00  15349.0 2004-10-01
21 2004-10-01 22:00:00  14837.0 2004-10-01
22 2004-10-01 23:00:00  14067.0 2004-10-01
23 2004-10-02 00:00:00  13147.0 2004-10-02
24 2004-10-02 01:00:00  12260.0 2004-10-02
25 2004-10-02 02:00:00  11672.0 2004-10-02
26 2004-10-02 03:00:00  11352.0 2004-10-02
27 2004-10-02 04:00:00  11177.0 2004-10-02
28 2004-10-02 05:00:00  11142.0 2004-10-02
29 2004-10-02 06:00:00  11331.0 2004-10-02
30 2004-10-02 07:00:00  11866.0 2004-10-02
31 2004-10-02 08:00:00  12387.0 2004-10-02
32 2004-10-02 09:00:00  13144.0 2004-10-02
33 2004-10-02 10:00:00  13712.0 2004-10-02
34 2004-10-02 11:00:00  14082.0 2004-10-02
35 2004-10-02 12:00:00  14080.0 2004-10-02
36 2004-10-02 13:00:00  14056.0 2004-10-02
37 2004-10-02 14:00:00  13934.0 2004-10-02
38 2004-10-02 15:00:00  13758.0 2004-10-02
39 2004-10-02 16:00:00  13579.0 2004-10-02
40 2004-10-02 17:00:00  13620.0 2004-10-02
41 2004-10-02 18:00:00  13483.0 2004-10-02
42 2004-10-02 19:00:00  13379.0 2004-10-02
43 2004-10-02 20:00:00  13825.0 2004-10-02
44 2004-10-02 21:00:00  14056.0 2004-10-02
45 2004-10-02 22:00:00  14015.0 2004-10-02
46 2004-10-02 23:00:00  12940.0 2004-10-02
47 2004-10-03 00:00:00  12172.0 2004-10-03
48 2004-10-03 01:00:00  11443.0 2004-10-03
49 2004-10-03 02:00:00  10807.0 2004-10-03

In [6]:
len(df)

121296

In [7]:
holiday=pd.read_csv(r'Z:\University\8th Semester\ML Lab\Lab 3\processed_holiday.csv',parse_dates=['Date'])

In [8]:
holiday.info()

<class 'pandas.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     279 non-null    datetime64[us]
 1   Holiday  279 non-null    str
 2   WeekDay  279 non-null    str
 3   Month    279 non-null    int64
 4   Day      279 non-null    int64
 5   Year     279 non-null    int64
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 13.2 KB

## Section 2: Holiday Dataset Inspection
The following cells load the processed holiday file, inspect its structure, and remove columns that are not required for merging.

In [9]:
holiday.head()

        Date                      Holiday   WeekDay  Month  Day  Year
0 2004-01-01               New Year's Day  Thursday      1    1  2004
1 2004-01-19  Martin Luther King, Jr. Day    Monday      1   19  2004
2 2004-02-14              Valentine’s Day  Saturday      2   14  2004
3 2004-02-16        Washington's Birthday    Monday      2   16  2004
4 2004-04-11               Eastern Easter    Sunday      4   11  2004

In [10]:
holiday.drop(['WeekDay','Month','Day','Year'],axis=1, inplace=True)

In [11]:
(len(holiday)*24)-(21*24) #in 2004 first 9 month is not include which includes 11 holidays.
                           #similarly in 2018 last 5 month not included which incluede 10 holidays.  21 total

6192

In [12]:
mergedf = pd.merge(df, holiday, on= 'Date', how="left")
mergedf

                  Datetime   AEP_MW       Date Holiday
0      2004-10-01 01:00:00  12379.0 2004-10-01     NaN
1      2004-10-01 02:00:00  11935.0 2004-10-01     NaN
2      2004-10-01 03:00:00  11692.0 2004-10-01     NaN
3      2004-10-01 04:00:00  11597.0 2004-10-01     NaN
4      2004-10-01 05:00:00  11681.0 2004-10-01     NaN
...                    ...      ...        ...     ...
121291 2018-08-02 20:00:00  17673.0 2018-08-02     NaN
121292 2018-08-02 21:00:00  17303.0 2018-08-02     NaN
121293 2018-08-02 22:00:00  17001.0 2018-08-02     NaN
121294 2018-08-02 23:00:00  15964.0 2018-08-02     NaN
121295 2018-08-03 00:00:00  14809.0 2018-08-03     NaN

[121296 rows x 4 columns]

In [13]:
#
mergedf['Holiday'].isna().sum()

np.int64(115104)

In [14]:
#121416
121296-mergedf['Holiday'].isna().sum()

np.int64(6192)

## .notnull()
 Creates a binary holiday feature where 1 means a holiday exists and 0 means no holiday.


Checks each row:

Returns True if the value is not null

Returns False if the value is null

## Section 3: Merging Main Data with Holiday Features
This section combines the AEP dataset with holiday information so that calendar effects can be used in later feature engineering.

In [15]:

mergedf['Holiday'] = mergedf['Holiday'].notnull().astype("int")

In [16]:
mergedf.head()

             Datetime   AEP_MW       Date  Holiday
0 2004-10-01 01:00:00  12379.0 2004-10-01        0
1 2004-10-01 02:00:00  11935.0 2004-10-01        0
2 2004-10-01 03:00:00  11692.0 2004-10-01        0
3 2004-10-01 04:00:00  11597.0 2004-10-01        0
4 2004-10-01 05:00:00  11681.0 2004-10-01        0

In [17]:
mergedf.to_csv(r'Z:\University\8th Semester\ML Lab\Lab 3\4_AEP_Introducing_holidays.csv',index=False)

In [18]:
mergedf[236:274]

               Datetime   AEP_MW       Date  Holiday
236 2004-10-10 21:00:00  14162.0 2004-10-10        0
237 2004-10-10 22:00:00  13770.0 2004-10-10        0
238 2004-10-10 23:00:00  13099.0 2004-10-10        0
239 2004-10-11 00:00:00  12346.0 2004-10-11        1
240 2004-10-11 01:00:00  11907.0 2004-10-11        1
241 2004-10-11 02:00:00  11614.0 2004-10-11        1
242 2004-10-11 03:00:00  11581.0 2004-10-11        1
243 2004-10-11 04:00:00  11514.0 2004-10-11        1
244 2004-10-11 05:00:00  11761.0 2004-10-11        1
245 2004-10-11 06:00:00  12558.0 2004-10-11        1
246 2004-10-11 07:00:00  14103.0 2004-10-11        1
247 2004-10-11 08:00:00  15277.0 2004-10-11        1
248 2004-10-11 09:00:00  15421.0 2004-10-11        1
249 2004-10-11 10:00:00  15501.0 2004-10-11        1
250 2004-10-11 11:00:00  15609.0 2004-10-11        1
251 2004-10-11 12:00:00  15554.0 2004-10-11        1
252 2004-10-11 13:00:00  15366.0 2004-10-11        1
253 2004-10-11 14:00:00  15365.0 2004-10-11        1
254 2004-10-11 15:00:00  15370.0 2004-10-11        1
255 2004-10-11 16:00:00  15217.0 2004-10-11        1
256 2004-10-11 17:00:00  15133.0 2004-10-11        1
257 2004-10-11 18:00:00  15059.0 2004-10-11        1
258 2004-10-11 19:00:00  15128.0 2004-10-11        1
259 2004-10-11 20:00:00  15995.0 2004-10-11        1
260 2004-10-11 21:00:00  15981.0 2004-10-11        1
261 2004-10-11 22:00:00  15417.0 2004-10-11        1
262 2004-10-11 23:00:00  14417.0 2004-10-11        1
263 2004-10-12 00:00:00  13402.0 2004-10-12        0
264 2004-10-12 01:00:00  12618.0 2004-10-12        0
265 2004-10-12 02:00:00  12277.0 2004-10-12        0
266 2004-10-12 03:00:00  12051.0 2004-10-12        0
267 2004-10-12 04:00:00  12052.0 2004-10-12        0
268 2004-10-12 05:00:00  12239.0 2004-10-12        0
269 2004-10-12 06:00:00  13072.0 2004-10-12        0
270 2004-10-12 07:00:00  14685.0 2004-10-12        0
271 2004-10-12 08:00:00  15784.0 2004-10-12        0
272 2004-10-12 09:00:00  15851.0 2004-10-12        0
273 2004-10-12 10:00:00  15846.0 2004-10-12        0

In [19]:
df.isnull().sum()

Datetime      0
AEP_MW      666
Date          0
dtype: int64

## Final Conclusion
In this lab, holiday information was added to the time-series dataset. This creates a richer dataset for future feature extraction and machine learning model development.